name: 'Release imdrasil project docs'
inputs:
  github_token:
    description: 'Token to push changes'
    required: true
  project_name:
    description: 'Project name'
    required: true
    default: 'all'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project_name }}
    - ${{ inputs.github_tocken }}
