name: 'Release imdrasil project docs'
inputs:
  github_token:
    description: 'Token to push changes'
    required: true
  project_name:
    description: 'Project name'
    required: true
    default: 'all'
  generate_script:
    required: false
    default: "crystal doc"
  exclude:
    required: false
    default: ""
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project_name }}
    - ${{ inputs.github_token }}
    - ${{ inputs.generate_script }}
    - ${{ inputs.exclude }}
